export const ROUTES = {
    HOME: "/",
    AUTHENTICATE:'/authenticate',
    ABOUT: "/about",
    CONTACT: "/contact",
    TRIP_PLAN:'/trip-plan',
    DESTINATIONS:'/destinations',
    PLAN_DETAILS:"/plan-details",
    VERIFY_EMAIL:"/verify-email" ,
    FORGOT_PASSWORD:"/forgot-password",  
    CREATE_ITINERARY:"/plan-details/itinerary", 
    EDIT_ITINERARY:"/dashboard/edit-itinerary",
    DASHBOARD:'/dashboard',
    TRIPS:"/trips",
    NOT_FOUND: "*", 
  };