const mustVisitPlaces = [
    { name: "Great Wall of China", country: "China" },
    { name: "Machu Picchu", country: "Peru" },
    { name: "Eiffel Tower", country: "France" },
    { name: "Taj Mahal", country: "India" },
    { name: "Colosseum", country: "Italy" },
    { name: "Grand Canyon", country: "USA" },
    { name: "Great Barrier Reef", country: "Australia" },
    { name: "Statue of Liberty", country: "USA" },
    { name: "Santorini", country: "Greece" },
    { name: "Kyoto’s Temples", country: "Japan" },
    { name: "Angkor Wat", country: "Cambodia" },
    { name: "Pyramids of Giza", country: "Egypt" },
    { name: "Niagara Falls", country: "Canada/USA" },
    { name: "Stonehenge", country: "UK" },
    { name: "Mount Fuji", country: "Japan" },
    { name: "Sagrada Familia", country: "Spain" },
    { name: "Sydney Opera House", country: "Australia" },
    { name: "Marrakech Medina", country: "Morocco" },
    { name: "Iguazu Falls", country: "Argentina/Brazil" },
    { name: "Banff National Park", country: "Canada" },
    { name: "The Louvre Museum", country: "France" },
    { name: "Petra", country: "Jordan" },
    { name: "Mount Everest", country: "Nepal" },
    { name: "The Acropolis", country: "Greece" },
    { name: "Dubrovnik Old Town", country: "Croatia" },
    { name: "Bora Bora", country: "French Polynesia" },
    { name: "Yellowstone National Park", country: "USA" },
    { name: "Reykjavik and the Golden Circle", country: "Iceland" },
    { name: "Great Smoky Mountains", country: "USA" },
    { name: "Bali", country: "Indonesia" },
    { name: "Cape Town and Table Mountain", country: "South Africa" },
    { name: "Barcelona’s Gothic Quarter", country: "Spain" },
    { name: "Vatican City", country: "Italy" },
    { name: "Galápagos Islands", country: "Ecuador" },
    { name: "Hagia Sophia", country: "Turkey" },
    { name: "Salar de Uyuni", country: "Bolivia" },
    { name: "Singapore Marina Bay Sands", country: "Singapore" },
    { name: "Dubai Burj Khalifa", country: "UAE" },
    { name: "Seoul’s Gyeongbokgung Palace", country: "South Korea" },
    { name: "Amsterdam Canals", country: "Netherlands" },
    { name: "Mount Kilimanjaro", country: "Tanzania" },
    { name: "Hokkaido’s Hot Springs", country: "Japan" },
    { name: "Hvar Island", country: "Croatia" },
    { name: "Buenos Aires", country: "Argentina" },
    { name: "Lisbon", country: "Portugal" },
    { name: "Vienna’s Historic Center", country: "Austria" },
    { name: "Walt Disney World", country: "USA" },
    { name: "Mumbai’s Gateway of India", country: "India" },
    { name: "Victoria Falls", country: "Zambia/Zimbabwe" },
    { name: "Oslo’s Vigeland Park", country: "Norway" },
    { name: "The Dead Sea", country: "Israel/Jordan" },
    { name: "Monte Carlo", country: "Monaco" },
    { name: "Andes Mountains", country: "South America" },
    { name: "Buenos Aires’ La Boca", country: "Argentina" },
    { name: "Rio de Janeiro’s Copacabana Beach", country: "Brazil" },
    { name: "Hong Kong Skyline", country: "Hong Kong" },
    { name: "Chichen Itza", country: "Mexico" },
    { name: "Zermatt and the Matterhorn", country: "Switzerland" },
    { name: "Cinque Terre", country: "Italy" },
    { name: "Siena’s Historic Center", country: "Italy" },
    { name: "Wellington", country: "New Zealand" },
    { name: "Mount Rushmore", country: "USA" },
    { name: "Giza Pyramids", country: "Egypt" },
    { name: "Venice’s St. Mark’s Basilica", country: "Italy" },
    { name: "Shibuya Crossing", country: "Japan" },
    { name: "Sydney Harbour", country: "Australia" },
    { name: "Luxor’s Karnak Temple", country: "Egypt" },
    { name: "Jerusalem Old City", country: "Israel" },
    { name: "Helsinki", country: "Finland" },
    { name: "Tokyo’s Shinjuku", country: "Japan" },
    { name: "Budapest’s Parliament Building", country: "Hungary" },
    { name: "Seville’s Alcázar", country: "Spain" },
    { name: "Cape Town’s V&A Waterfront", country: "South Africa" },
    { name: "Sapporo Snow Festival", country: "Japan" },
    { name: "Moscow’s Red Square", country: "Russia" },
    { name: "Goreme National Park", country: "Turkey" },
    { name: "Athens’ Parthenon", country: "Greece" },
    { name: "Dublin’s Temple Bar", country: "Ireland" },
    { name: "The Great Barrier Reef", country: "Australia" },
    { name: "Edinburgh Castle", country: "Scotland" },
    { name: "Athens’ Plaka", country: "Greece" },
    { name: "South Island’s Fjords", country: "New Zealand" },
    { name: "Hong Kong’s Victoria Peak", country: "Hong Kong" },
    { name: "Malta’s Valetta", country: "Malta" }
];


export default mustVisitPlaces;